logging:
  level:
    root: INFO
    sql: DEBUG
    projects.finalproject: DEBUG
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/final_project?useSSL=false&serverTimezone=UTC
    username: root
    password: testpass
